[package]
name = "coffeeshop"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-dynamodb = "1.55.0"
aws-sdk-sqs = "1.50.0"
aws-sdk-sts = "1.51.0"
axum = "0.7.9"
base64 = "0.22.1"
clap = { version = "4.5.23", features = ["derive"] }
hashbrown = "0.15.2"
prost = "0.13.4"
prost-types = "0.13.4"
rmp-serde = "1.3.0"
serde = "1.0.215"
thiserror = "2.0.6"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "signal", "sync"] }

[build-dependencies]
prost-build = "0.13.4"
